package server.db;

import common.network.*;
import org.hibernate.Session;
import org.hibernate.Transaction;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class StudyBotDAO {
    public boolean courseExists(int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){Number n=(Number)s.createNativeQuery("SELECT COUNT(*) FROM Courses WHERE id=:c").setParameter("c",courseId).uniqueResult();return n!=null&&n.longValue()>0;}}
    public boolean teacherCanEdit(int teacherId,int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){Number n=(Number)s.createNativeQuery("SELECT COUNT(*) FROM CourseTeachers ct JOIN Users u ON u.id=ct.teacher_id WHERE ct.teacher_id=:t AND ct.course_id=:c AND u.role='TEACHER'").setParameter("t",teacherId).setParameter("c",courseId).uniqueResult();return n!=null&&n.longValue()>0;}}
    public StudyBotView createBot(int courseId,String name,boolean includeQuestionBank,int teacherId){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();int n=s.createNativeMutationQuery("INSERT IGNORE INTO StudyBots(course_id,name,created_by,available,include_question_bank) VALUES(:c,:n,:t,0,:q)").setParameter("c",courseId).setParameter("n",name).setParameter("t",teacherId).setParameter("q",includeQuestionBank).executeUpdate();if(n==0)throw new IllegalArgumentException("A study bot already exists for this course.");tx.commit();return getBot(courseId);}catch(RuntimeException e){Transactions.rollbackQuietly(tx);throw e;}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException("Could not create study bot.",e);}}
    public StudyBotView getBot(int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){Object[] r=(Object[])s.createNativeQuery("SELECT b.course_id,b.name,b.available,b.include_question_bank,b.created_by,b.created_at,COUNT(src.id) FROM StudyBots b LEFT JOIN StudyBotSources src ON src.course_id=b.course_id WHERE b.course_id=:c GROUP BY b.course_id,b.name,b.available,b.include_question_bank,b.created_by,b.created_at").setParameter("c",courseId).uniqueResult();return bot(r);}}
    public boolean botAvailable(int courseId){StudyBotView b=getBot(courseId);return b!=null&&b.isAvailable();}
    public StudyBotView setAvailability(int courseId,boolean available){mutate("UPDATE StudyBots SET available=:a WHERE course_id=:c",s->s.setParameter("a",available).setParameter("c",courseId),"Could not update study-bot availability.");return getBot(courseId);}
    public StudyBotSourceView addSource(int courseId,String title,String content,StudyBotSourceType type,String originalFileName,int userId){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();s.createNativeMutationQuery("INSERT INTO StudyBotSources(course_id,title,content,source_type,original_filename,created_by,updated_by,updated_at) VALUES(:c,:t,:x,:st,:f,:u,:u,NOW())").setParameter("c",courseId).setParameter("t",title).setParameter("x",content).setParameter("st",type.name()).setParameter("f",originalFileName).setParameter("u",userId).executeUpdate();Number id=(Number)s.createNativeQuery("SELECT LAST_INSERT_ID()").uniqueResult();tx.commit();return getSource(id.intValue());}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException("Could not add study-bot source.",e);}}
    public StudyBotSourceView addSource(int courseId,String title,String content,int userId){return addSource(courseId,title,content,StudyBotSourceType.TEXT,null,userId);}
    public StudyBotSourceView getSource(int id){try(Session s=HibernateUtil.getSessionFactory().openSession()){return source((Object[])s.createNativeQuery("SELECT id,course_id,title,content,source_type,original_filename,updated_by,updated_at FROM StudyBotSources WHERE id=:i").setParameter("i",id).uniqueResult());}}
    public StudyBotSourceView updateSource(int id,String title,String content,int userId){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();int n=s.createNativeMutationQuery("UPDATE StudyBotSources SET title=:t,content=:x,source_type='TEXT',original_filename=NULL,updated_by=:u,updated_at=NOW() WHERE id=:i").setParameter("t",title).setParameter("x",content).setParameter("u",userId).setParameter("i",id).executeUpdate();tx.commit();return n==0?null:getSource(id);}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException("Could not update study-bot source.",e);}}
    public boolean deleteSource(int id){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();int n=s.createNativeMutationQuery("DELETE FROM StudyBotSources WHERE id=:i").setParameter("i",id).executeUpdate();tx.commit();return n>0;}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException("Could not delete study-bot source.",e);}}
    public List<StudyBotSourceView> getSources(int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){List<?> rows=s.createNativeQuery("SELECT id,course_id,title,content,source_type,original_filename,updated_by,updated_at FROM StudyBotSources WHERE course_id=:c ORDER BY id").setParameter("c",courseId).list();List<StudyBotSourceView> out=new ArrayList<>();for(Object o:rows)out.add(source((Object[])o));return out;}}
    public List<String> getQuestionBankContext(int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){List<?> rows=s.createNativeQuery("SELECT question_text,answer_1,answer_2,answer_3,answer_4,correct_answer FROM Questions WHERE course_id=:c AND is_current=1 ORDER BY id").setParameter("c",courseId).list();List<String> out=new ArrayList<>();for(Object o:rows){Object[]r=(Object[])o;int correct=((Number)r[5]).intValue();out.add("Question: "+r[0]+"\n1. "+r[1]+"\n2. "+r[2]+"\n3. "+r[3]+"\n4. "+r[4]+"\nCorrect answer: "+correct);}return out;}}
    public StudyBotAnswer saveHistory(int courseId,int studentId,String q,String a,String status){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();s.createNativeMutationQuery("INSERT INTO StudyBotHistory(course_id,student_id,question,answer,status,asked_at) VALUES(:c,:u,:q,:a,:st,NOW())").setParameter("c",courseId).setParameter("u",studentId).setParameter("q",q).setParameter("a",a).setParameter("st",status).executeUpdate();Number id=(Number)s.createNativeQuery("SELECT LAST_INSERT_ID()").uniqueResult();Object[] r=(Object[])s.createNativeQuery("SELECT id,course_id,question,answer,status,asked_at FROM StudyBotHistory WHERE id=:i").setParameter("i",id.intValue()).uniqueResult();tx.commit();return answer(r);}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException("Could not save study-bot history.",e);}}
    public StudyBotAnswer saveHistory(int c,int s,String q,String a){return saveHistory(c,s,q,a,"ANSWERED");}
    public List<StudyBotAnswer> personalHistory(int studentId){try(Session s=HibernateUtil.getSessionFactory().openSession()){List<?> rows=s.createNativeQuery("SELECT id,course_id,question,answer,status,asked_at FROM StudyBotHistory WHERE student_id=:u ORDER BY asked_at DESC").setParameter("u",studentId).list();List<StudyBotAnswer> out=new ArrayList<>();for(Object o:rows)out.add(answer((Object[])o));return out;}}
    public StudyBotUsageReport usage(int courseId){try(Session s=HibernateUtil.getSessionFactory().openSession()){Object[] counts=(Object[])s.createNativeQuery("SELECT COUNT(*),COUNT(DISTINCT student_id) FROM StudyBotHistory WHERE course_id=:c").setParameter("c",courseId).uniqueResult();List<?> rows=s.createNativeQuery("SELECT question,asked_at FROM StudyBotHistory WHERE course_id=:c ORDER BY asked_at DESC LIMIT 100").setParameter("c",courseId).list();List<StudyBotUsageReport.Entry> entries=new ArrayList<>();for(Object o:rows){Object[]r=(Object[])o;entries.add(new StudyBotUsageReport.Entry((String)r[0],time(r[1])));}List<?> commonRows=s.createNativeQuery("SELECT MIN(question),COUNT(*) n FROM StudyBotHistory WHERE course_id=:c GROUP BY LOWER(TRIM(question)) ORDER BY n DESC,MIN(question) LIMIT 10").setParameter("c",courseId).list();List<CommonQuestion> common=new ArrayList<>();for(Object o:commonRows){Object[]r=(Object[])o;common.add(new CommonQuestion((String)r[0],((Number)r[1]).longValue()));}return new StudyBotUsageReport(courseId,((Number)counts[0]).longValue(),((Number)counts[1]).longValue(),entries,common);}}
    private interface Binder{org.hibernate.query.MutationQuery bind(org.hibernate.query.MutationQuery q);} private void mutate(String sql,Binder b,String message){Transaction tx=null;try(Session s=HibernateUtil.getSessionFactory().openSession()){tx=s.beginTransaction();b.bind(s.createNativeMutationQuery(sql)).executeUpdate();tx.commit();}catch(Exception e){Transactions.rollbackQuietly(tx);throw new IllegalStateException(message,e);}}
    private static boolean bool(Object v){if(v instanceof Boolean)return(Boolean)v;if(v instanceof Number)return((Number)v).intValue()!=0;return v!=null&&Boolean.parseBoolean(v.toString());}
    private static StudyBotView bot(Object[]r){return r==null?null:new StudyBotView(((Number)r[0]).intValue(),(String)r[1],bool(r[2]),bool(r[3]),((Number)r[4]).intValue(),time(r[5]),((Number)r[6]).longValue());}
    private static StudyBotSourceView source(Object[]r){return r==null?null:new StudyBotSourceView(((Number)r[0]).intValue(),((Number)r[1]).intValue(),(String)r[2],(String)r[3],StudyBotSourceType.valueOf(String.valueOf(r[4])),(String)r[5],((Number)r[6]).intValue(),time(r[7]));}
    private static StudyBotAnswer answer(Object[]r){return new StudyBotAnswer(((Number)r[0]).intValue(),((Number)r[1]).intValue(),(String)r[2],(String)r[3],String.valueOf(r[4]),time(r[5]));}
    private static LocalDateTime time(Object o){return o instanceof Timestamp?((Timestamp)o).toLocalDateTime():(LocalDateTime)o;}
}
