package server.db;

import common.entities.Question;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static server.db.QuestionBankTestFixture.COURSE_ALGORITHMS;
import static server.db.QuestionBankTestFixture.COURSE_DATABASES;

/**
 * Scenario 2.1 — adding a question to the bank (Person 2, Phase 2).
 *
 * <p>Locks down {@link QuestionDAO#add}: id/family bookkeeping of a brand-new
 * question, full field round-trip, visibility in the read queries, and clean
 * failure on a broken foreign key.
 */
class QuestionDAOAddTest extends QuestionDaoTestBase {

    @Test
    void addStampsIdFamilyAndVersion() {
        Question saved = dao.add(QuestionBankTestFixture.sample(COURSE_ALGORITHMS));

        assertThat(saved).isNotNull();
        assertThat(saved.getId()).isPositive();
        assertThat(saved.getBaseId())
                .as("a new question is its own version family")
                .isEqualTo(saved.getId());
        assertThat(saved.getVersion()).isEqualTo(1);
        assertThat(saved.isCurrent()).isTrue();
    }

    @Test
    void addedQuestionAppearsInBankAndCourseQueries() {
        Question saved = dao.add(QuestionBankTestFixture.sample(COURSE_ALGORITHMS));

        assertThat(dao.getAllCurrent())
                .extracting(Question::getId).containsExactly(saved.getId());
        assertThat(dao.getByCourse(COURSE_ALGORITHMS))
                .extracting(Question::getId).containsExactly(saved.getId());
        assertThat(dao.getByCourse(COURSE_DATABASES))
                .as("other courses are unaffected")
                .isEmpty();
    }

    @Test
    void everyFieldSurvivesTheRoundTrip() {
        Question original = new Question(
                COURSE_DATABASES,
                "Which normal form removes transitive dependencies?",
                "1NF", "2NF", "3NF", "BCNF",
                3,
                "diagrams/3nf.png",
                "Normalization",
                "HARD");

        dao.add(original);
        Question loaded = dao.getByCourse(COURSE_DATABASES).get(0);

        assertThat(loaded)
                .usingRecursiveComparison()
                .ignoringFields("id", "baseId")   // generated by the DB
                .isEqualTo(original);
    }

    @Test
    void addWithUnknownCourseFailsCleanly() {
        Question orphan = QuestionBankTestFixture.sample(9999);   // no such course

        Question result = dao.add(orphan);

        assertThat(result).as("FK violation must surface as null, not an exception").isNull();
        assertThat(dao.getAllCurrent()).as("no partial row may remain").isEmpty();
    }
}
